<?php
/**
 * HackMeBank Database Configuration
 * Generated by installation script on 2025-04-29 20:37:18
 */

return [
    'host'      => 'localhost',
    'database'  => 'hackmebank',
    'username'  => 'root',
    'password'  => '',
    'charset'   => 'utf8mb4',
    'collation' => 'utf8mb4_unicode_ci',
    'prefix'    => '',
];
